apiVersion: v1
kind: Service
metadata:
  name: deep-food-api-service
spec:
  selector:
    app: deep-food-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
  type: LoadBalancer 
